/* WAREHOUSE MANAGEMENT SYSTEM */

// Tarefas - todas disponíveis no ERP/WMS Sankhya
final tarefas = [
  {
    'codtarefa': 1,
    'descrtarefa': 'Conferência',
    'rota': 'conferencia',
    'icone': '',
    'ativo': true,
  },
  {
    'codtarefa': 2,
    'descrtarefa': 'Armazenagem',
    'rota': 'armazenagem',
    'icone': '',
    'ativo': true,
  },
  {
    'codtarefa': 3,
    'descrtarefa': 'Separação',
    'rota': 'separacao',
    'icone': '',
    'ativo': true,
  },
  {
    'codtarefa': 4,
    'descrtarefa': 'Reabastecimento',
    'rota': '',
    'icone': '',
    'ativo': true,
  },
  {
    'codtarefa': 5,
    'descrtarefa': 'Transferência',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 6,
    'descrtarefa': 'Contagem de Estoque',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 7,
    'descrtarefa': 'Conferência Entrada',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 8,
    'descrtarefa': 'Conferência Saída',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 9,
    'descrtarefa': 'Recepção da Produção',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 10,
    'descrtarefa': 'Recep. Prod. com divergência',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 11,
    'descrtarefa': 'Consulta de Estoque',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 12,
    'descrtarefa': 'Conferência de Volumes',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 13,
    'descrtarefa': 'Conferência por Pedido',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 14,
    'descrtarefa': 'Avaria',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 15,
    'descrtarefa': 'Reabastecimento Corretivo',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 16,
    'descrtarefa': 'Consulta de Produtos',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 17,
    'descrtarefa': 'Separação Balcão',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 18,
    'descrtarefa': 'Movimentação Pró-Ativa',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 19,
    'descrtarefa': 'Consulta de O.C.',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 20,
    'descrtarefa': 'Redefinição Dt.Validade',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 21,
    'descrtarefa': 'Armazenagem Seletiva',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 22,
    'descrtarefa': 'Formação de Volumes',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 23,
    'descrtarefa': 'Conferência parcial de entrada',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 24,
    'descrtarefa': 'Armazenamento Expresso',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 25,
    'descrtarefa': 'Registro de Volumes',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 26,
    'descrtarefa': 'Separação por Esteira',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 27,
    'descrtarefa': 'Separação por Área',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 28,
    'descrtarefa': 'Triagem de Pedidos',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 29,
    'descrtarefa': 'Registro de Conferência',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 30,
    'descrtarefa': 'Triagem Crossdocking',
    'rota': '',
    'icone': '',
    'ativo': false,
  },
  {
    'codtarefa': 31,
    'descrtarefa': 'Conferência por Peça',
    'rota': '',
    'icone': '',
    'ativo': false,
  }
];
